// Test generated by RoostGPT for test golang-test-shakul using AI Type Open AI and AI Model gpt-4

package main

import (
	"testing"
)

func checkPrimeNumber(num int) bool {
	var i int
	for i = 2; i < num; i++ {
		if num%i == 0 {
			return false
		}
	}

	if num == i {
		return true
	}

	return false
}

func TestCheckPrimeNumber(t *testing.T) {
	testCases := []struct {
		name     string
		input    int
		expected bool
	}{
		{
			name:     "Test Case 1: Prime Number",
			input:    7,
			expected: true,
		},
		{
			name:     "Test Case 2: Non-Prime Number",
			input:    4,
			expected: false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := checkPrimeNumber(tc.input)
			if result != tc.expected {
				t.Errorf("For %d, expected %v, but got %v", tc.input, tc.expected, result)
			}
		})
	}
}
