// Test generated by RoostGPT for test golang-test-shakul using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package mytest

import (
	"testing"
)

func TestIsEven(t *testing.T) {
	// Success scenario
	result := is_even(4)
	if result!= 1 {
		t.Errorf("Expected %d but got %d", 1, result)
	}

	// Failure scenario
	result = is_even(-1)
	if result!= 0 {
		t.Errorf("Expected %d but got %d", 0, result)
	}

	// Edge case
	result = is_even(3)
	if result!= 0 {
		t.Errorf("Expected %d but got %d", 0, result)
	}
}

func TestIsOdd(t *testing.T) {
	// Success scenario
	result := is_even(5)
	if result!= 0 {
		t.Errorf("Expected %d but got %d", 0, result)
	}

	// Failure scenario
	result = is_even(2)
	if result!= 1 {
		t.Errorf("Expected %d but got %d", 1, result)
	}

	// Edge case
	result = is_even(6)
	if result!= 0 {
		t.Errorf("Expected %d but got %d", 0, result)
	}
}
