// Test generated by RoostGPT for test golang-test-shakul using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package main

import (
	"fmt"
	"testing"
)

func TestFibonacci(t *testing.T) {
	// Test case 1: Fibonacci of 0
	t.Run("Zero", func(t *testing.T) {
		res := fib(0)
		expected := ""
		if res!= expected {
			t.Errorf("Expected %v, got %v", expected, res)
		}
	})

	// Test case 2: Fibonacci of 1
	t.Run("One", func(t *testing.T) {
		res := fib(1)
		expected := "1"
		if res!= expected {
			t.Errorf("Expected %v, got %v", expected, res)
		}
	})

	// Test case 3: Fibonacci of 2
	t.Run("Two", func(t *testing.T) {
		res := fib(2)
		expected := "2 1"
		if res!= expected {
			t.Errorf("Expected %v, got %v", expected, res)
		}
	})

	// Test case 4: Fibonacci of 3
	t.Run("Three", func(t *testing.T) {
		res := fib(3)
		expected := "3 2 1"
		if res!= expected {
			t.Errorf("Expected %v, got %v", expected, res)
		}
	})

	// Test case 5: Fibonacci of negative number
	t.Run("Negative", func(t *testing.T) {
		res := fib(-1)
		expected := "0"
		if res!= expected {
			t.Errorf("Expected %v, got %v", expected, res)
		}
	})
}
